---
title: "H3K27ac_HGSOC_consensus_upsetr_analysis"
author: "Alberto Luiz Pascasio Reyes"
date: "10/25/2018"
output: html_document
---

load libraries and input files
```{r}

library(GenomicRanges)
library(HelloRanges)
library(readr)
library(dplyr)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(UpSetR)
library(rtracklayer)
library(optparse)
library(pheatmap)

hgsoc_k27ac_hg19 <- read_table2("hg19_H3K27ac_biofeature_beds/HGSOC/allpeaks.anno.tsv") ### file made from simon's bash script

```


do analysis upsetr analysis
```{r}

# option_list <- list(
#   make_option(c("-f", "--file"), type = "character", default = NULL,
#               help = "dataset file name", metavar = "character"),
#   make_option(c("-o", "--out"), type = "character",
#               default = "consensus_out",
#               help = "output file name [default= %default]",
#               metavar = "character")
# )
# 
# opt_parser <- OptionParser(option_list = option_list);
# opt <- parse_args(opt_parser);
# 
# if (is.null(opt$file)){
#   print_help(opt_parser)
#   stop("At least one argument must be supplied (input file).n", call.=FALSE)
# }
# 
# if (!file.exists(opt$file)) {
#   stop("File ", opt$file, "does not exist")
# } ### not working yet

x <- hgsoc_k27ac_hg19[,-8]
y <- x; y[, c(4:ncol(x))] <- x[, c(4:ncol(x))] > 0.5

y <- GRanges(seqnames = y$chr,
             ranges = IRanges(start = y$start, end = y$end - 1),
             data = y[, 4:ncol(y)])

yr <- GenomicRanges::reduce(y, with.revmap = TRUE)

sample_overlap <- t(bind_cols(lapply(
  relist(mcols(y)[unlist(yr$revmap),], yr$revmap),
  function(x) {
    tibble::as_tibble(colSums(as.matrix(x)) >= 1) ### set threshold of overlap (percentage) here
  })))

mcols(yr) <- sample_overlap
colnames(sample_overlap) <- gsub("data.", "", colnames(mcols(y)))
yr$sample_count <- rowSums(as.matrix(mcols(yr)))

# file_ranges <- yr
# save(file_ranges, sample_overlap, file = paste0(opt$out, "_rdata.rda"))
# 
# pdf(paste0(opt$out, "_upset.pdf")) ### not yet working

upset(as.data.frame(sample_overlap + 0), ### simon's method
      order.by = "freq",
      text.scale = c(2, 2, 2, 1.5, 2.25, 2.25),
      point.size = 5) ### use this method bc of reduce step (ie bedtools merge) --> doesn't double count peaks, instead uses our defn of inclusive boundaries
######### looks very different than first correction attempt (but this one is correct bc last time used WRONG input files)

# dev.off()
# 
# for (peak_count in c(1:ncol(mcols(y)))) {
#   rtracklayer::export.bed(yr[yr$sample_count == peak_count, ],
#                           paste0(opt$out, "_", peak_count, "_samples.bed"))
# } ### not working yet

```

try cluster analysis
```{r}

pheatmap(as.matrix(x[1:1000,4:7])) ### clustering "works" but not meaningful w/ just presence of peak (esp. bc all peaks used)???

```






